openapi: 3.1.0
info:
  version: "1.0.0"
  title: Simple Go Web Application

components:
  schemas:
    NotesResponse:
      type: object
      properties:
        description:
          type: string
          example: "some description"
        tags:
          type: array
          items:
            type: string
          example:
            - "tag1"
        contents:
          type: array
          items:
            type: string
          example:
            - "line1"

paths:
  /:
    get:
      summary: Retrieves greeting messages
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 2
                  notes:
                    type: array
                    items:
                      $ref: "#/components/schemas/NotesResponse"
              example:
                count: 2
                notes:
                  - description: "some description"
                    tags:
                      - "tag1"
                      - "tag2"
                    contents:
                      - "line1"
                      - "line2"
                  - description: "another description"
                    tags:
                      - "tag3"
                    contents:
                      - "line3"
        "405":
          description: Invalid request method
          content:
            application/json:
              schema:
                type: string
              example: "Only GET requests are allowed on this endpoint."
